"""
Copyright (C) J Leadbetter <j@jleadbetter.com>
Affero GPL v3
"""

import uuid
from typing import List, Optional

from pydantic import BaseModel

from .base import HashableMixin
from .files import BinaryFileData
from .users import UserUI
from ..utils.languages import LanguageCode


class DocumentBase(HashableMixin):
    """
    Shared base class for the Pydantic models for the database.

    Must implement the following fields:

    * id
    * user (with user.id)
    * language_code
    """
    pass


class DocumentDB(DocumentBase, BaseModel):
    """
    Representation of a document to be stored in the database
    """

    id: Optional[uuid.UUID] = None  # Generated by the database when created.
    user_id: uuid.UUID  # UserProfile uuid
    display_name: str
    language_code: LanguageCode
    file_path: Optional[str] = None
    binary_data: Optional[BinaryFileData] = None
    translations: Optional[List['DocumentDB']] = None

    @property
    def unique_fields(self):
        return ['user_id', 'display_name', 'language_code']


class DocumentUIMinimal(DocumentBase, BaseModel):
    """
    Bare minimum display of documents in the UI
    Excludes Sentences and Words
    """

    id: uuid.UUID
    user: UserUI
    displayName: str
    language: str


class DocumentUI(DocumentBase, BaseModel):
    """
    Full document for display in the UI
    """

    id: uuid.UUID
    user: UserUI
    displayName: str
    language: str
    # TODO: rest of the model
